import numpy as np
import numpy.typing as npt




class Integrator():
    """
    Simple Monte Carlo integrator for estimating integrals over the unit hypercube.
    
    This class computes the integral of a function `f` over [0, 1)^dimension 
    using the provided sample points (typically generated by a Sampler).
    
    It is designed to work with any of the samplers in this library 
    (Uniform, Halton, Sobol, Lattice, etc.).
    
    Parameters
    ----------
    f : callable
        Function to integrate. It should accept a 1D array of length `dimension`
        and return a scalar (float or int).
    samples : npt.NDArray
        Array of shape (n_samples, dimension) containing sampling points
        in the unit hypercube [0, 1)^dimension.
    """
    def __init__(self,f:callable ,samples :npt.NDArray):
        self.f = np.vectorize(f, signature =f"({samples.shape[1]}) -> ()")
        self.samples = samples
    def compute(self) -> float:
        """
        Compute the Monte Carlo estimate of the integral.
        
        The integral is approximated by the average value of the function
        evaluated at the sample points:
        
            ∫_{[0,1)^d} f(x) dx ≈ (1/N) * Σ f(x_i)
        
        Returns
        -------
        float
            The estimated value of the integral.
        """
        n = self.samples.shape[0]
        return (1/n)*np.sum(self.f(self.samples))
    
    






