[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "qmc-lib"
version = "0.1.0"
description = "Monte Carlo and Quasi-Monte Carlo library for numerical integration"
authors = [
    {name = "Samuel Vangu"}
]
dependencies = [
    "numpy",
    "matplotlib"
]

[tool.setuptools.packages.find]
where = ["src"]
